# Generated by Django 4.2.3 on 2023-10-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_photo_task_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='photo',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='application.photo'),
        ),
    ]
